name: Push_Workflow
on: 
    push:
        branches:
        - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo " This is my first workflow"
      - name: print the status
        run: |
          echo "Welcome to thhe project"
          echo "Executed successfully"
          echo "push executed successfully and switched from workflow trigger to push trigger"